Vagrant.configure("2") do |config|
    config.vm.define "zabix" do |zabix|
        config.ssh.insert_key= false
        zabix.vm.box ="peru/ubuntu-20.04-server-amd64"
        zabix.vm.hostname = "monitoring-node"
        zabix.vm.network "private_network", ip: "192.168.50.50"
        zabix.vm.provision "shell", path: "create.sh"
        zabix.vm.provider "virtualbox" do |vb|
            vb.name = "monitor"
            vb.cpus = "2"
            vb.gui = false
            vb.gui = 4096
        end
    end
end