
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"  
  config.vm.network "private_network", ip: "192.168.50.50"
  config.vm.define "ansible-controller"
  config.vm.hostname = "ansible-controller"
  config.vm.provision "ansible_local" do | ansible |    
    ansible.playbook ="controller.yaml"
    ansible.inventory_path = "inventory"
    ansible.install = true
    ansible_ssh_private_key_file="/vagrant/insecure_private_key" 
    ansible.limit = 'all'
    ansible.verbose = true   
  end
end   

