Vagrant.configure("2") do |config|
    config.vm.define "manager" do |manager|
        config.ssh.insert_key = false
        manager.vm.box="peru/ubuntu-20.04-server-amd64"
        manager.vm.hostname = "manager"
        manager.vm.synced_folder ".", "/vagrant", type: "virtualbox"                 
        manager.vm.network "private_network", ip: "192.168.50.10"
        manager.vm.network "forwarded_port", guest: 80, host: 3000        
        manager.vm.provision "shell", path: "manager.sh"
        manager.vm.provider "virtualbox" do |vb|
            vb.name = "manager"             
            vb.gui = false
            vb.memory = 1048
        end
    end

    config.vm.define "proxy" do | proxy |
      config.ssh.insert_key = false
      proxy.vm.box = "peru/ubuntu-20.04-server-amd64"
      proxy.vm.hostname = "proxy"
      proxy.vm.synced_folder  "." , "/vagrant", type: "virtualbox"
      proxy.vm.network "private_network", ip: "192.168.50.20"
      proxy.vm.provision "shell", path: "haproxy.sh"
      proxy.vm.provider "virtualbox" do | vb |
        vb.name = "proxy"
        vb.gui = false
        vb.memory = 1048
      end
    end

    (1..3).each do |i|
        config.vm.define "worker#{i}" do |worker|
          worker.vm.box = "peru/ubuntu-20.04-server-amd64"      
          worker.vm.hostname = "worker#{i}"
          worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"  
          worker.vm.network "private_network", ip: "192.168.50.10#{i}"                   
          worker.vm.provision "shell" , path: "worker.sh"
          worker.vm.provider "virtualbox" do |vb|
            vb.name = "worker#{i}"
            vb.cpus = "1"
            vb.gui = false
            vb.memory = "1048"
          end
        end
    end
end