Vagrant.configure("2") do |config|
    config.vm.define "controller" do |controller|
      config.ssh.insert_key = false
      controller.vm.box = "peru/ubuntu-20.04-server-amd64"
      controller.vm.hostname = "controller"
      controller.vm.network "private_network", ip: "192.168.50.10"
      controller.vm.provision "shell", path: "master.sh"   
      controller.vm.provider "virtualbox" do |vb|
        vb.name = "master" 
        vb.cpus = 2         
        vb.gui = false     
        vb.memory = "4096"          
      end
    end
    
    (1..2).each do |i|
      config.vm.define "node#{i}" do |node|
        node.vm.box = "peru/ubuntu-20.04-server-amd64"      
        node.vm.hostname = "node#{i}"
        node.vm.network "private_network", ip: "192.168.50.10#{i}"
        node.vm.provision "shell" , path: "node.sh"
        node.vm.provider "virtualbox" do |vb|
          vb.name = "node#{i}"
          vb.gui = false          
          vb.memory = "1048"
        end
      end
    end
end    

    