---
- hosts: all
  become: True
  tasks:
    - name: configure the hostname for the master node
      hostname:
        name: k8-master

    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - containerd


    - name: configuring pre-requsite
      shell : |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

        sudo modprobe overlay
        sudo modprobe br_netfilter

        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF
        sudo sysctl --system
        exit 0    

    - name: create directory for conatinerd configuration 
      file: 
        path: /etc/containerd
        state: directory

    - name: run the shell command and create the file 
      shell: |
        containerd config default | sudo tee /etc/containerd/config.toml
        exit 0

    - name: remove the line in file
      lineinfile:
        path: /etc/containerd/config.toml
        state: present
        regexp: '            SystemdCgroup = false'
        line: '            SystemdCgroup = True'


    - name: download the apt key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Install Apt Key from File
      apt_key:        
        file: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: Kubernetes Apt Repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes       
        update_cache: true


    - name: install kubelet kubadm and kubectl on master node
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - kubelet
        - kubeadm 
        - kubectl

    
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init 


    - name: Setup kubeconfig for Ansible user
      file:
        state: directory
        path: /home/ansible/.kube
        owner: ansible
        group: ansible

    - name: copy kubernetes admin file
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ansible/.kube/config
        owner: ansible
        group: ansible
        remote_src: yes     
       

    - name: Install calico pod network
      become: false
      command: kubectl create -f https://projectcalico.docs.tigera.io/manifests/calico.yaml 

    - name: Remove swap
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0  

    - name: Generate join command   
      shell: kubeadm token create --print-join-command        
      register: join_command


    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"   
