Vagrant.configure("2") do |config|
    config.vm.define "gitlab" do | gitlabrunner |
        config.ssh.insert_key = false
        gitlabrunner.vm.box="peru/ubuntu-20.04-server-amd64"
        gitlabrunner.vm.hostname = "GitLab-Ubuntu-Runner"
        gitlabrunner.vm.synced_folder ".", "/vagrant", type: "virtualbox"                 
        gitlabrunner.vm.network "private_network", ip: "192.168.50.10"              
        gitlabrunner.vm.provision "shell", path: "package.sh"
        gitlabrunner.vm.provider "virtualbox" do |vb|
            vb.name = "gitlabrunner"             
            vb.gui = false
            vb.memory = 2048
        end
    end 
end